### ISSUE TITLE
Reconhecimento das variáveis de ambiente do Amazon S3 e funcionamento do upload

### ISSUE THREAD

**Issue by denisprado** [startae/uploadbox#10]
Estou com dois problemas ao utilizar o uploadbox. Um é que todo servidor de desenvolvimento que utilizo me pede para setar as variáveis do S3. Como eu poderia deixar essas variáveis armazenadas? Eu poderia utilizar config.storage = :file e vez de config.storage = :fog no uploadbox.rb? 

Outro problema é que quando seleciono uma imagem para fazer upload, nada acontece, nenhum log de erro inclusive. Alguma dica do que poderia ser?

**Comment by denisprado** [comment]
O segundo problema foi resolvido, aparentemente. Adicionei a gem 'coffee-script-source', '1.8.0' e rodei o bundle update. O Uploadbox está funcionando.

**Comment by renatocarvalho** [comment]
Opa @denisprado, conseguiu resolver os dois problemas?

**Comment by denisprado** [comment]
No primeiro, quando estou em ambiente de desenvolvimento Windows, ainda tenho que setar as variáveis. No Mac consegui deixar no bash profile. Bem, não é um grande problema... :)

No segundo caso, aparentemente a atualização do coffee-script-source resolveu para o ambiente de produção pelo menos.

Aproveitando, queria perguntar: existe previsão de documentação para o uploads_many? E existe uma maneira de utilizar o uploadbox no activeadmin?

**Comment by romulomachado** [comment]
@denisprado Te respondi lá na superquadra.

Sobre a documentação do uploads_many, vou ver o que posso fazer aqui e te mando notícias em breve.

O uploadbox no active admin rola com um hackzinho:

```
form do |f|
  f.inputs do
    f.input :title
    li class: 'string input optional stringish', id: 'post_image_input', style: 'overflow: hidden;' do
      label :image
      div style: 'width: 80%; float: right; display: inline-block;' do
        f.uploads_one :image
      end
    end
    f.input :body, input_html: { class: "redactor" }
    f.input :author
    f.input :category
    f.input :published
  end
  f.actions
end
```

**Comment by denisprado** [comment]
Oi Rômulo, tudo bem?

Alguma novidade quanto ao uploads_many?

valeu! :)

Denis Forigo

------------------------------------------------------------
Camará comunicação e educação popular <http://www.camaracom.com.br>
http://www.camaracom.com.br
------------------------------------------------------------

2015-03-22 20:57 GMT-03:00 Rômulo Machado <notifications@github.com>:

**Comment by romulomachado** [comment]
@denisprado E aí, rapaz!

Desculpa pela demora, se ainda estiver precisando da documentação do `uploads_many`, acabei de atualizar o README.

https://github.com/startae/uploadbox#uploads_many
