### ISSUE TITLE
Erro ao rodar comando "rails g uploadbox:image"

### ISSUE THREAD

**Issue by tporto** [startae/uploadbox#9]
Estou usando o HAML como template, e quando fui gerar os arquivos da esse erro,

/Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- slim (LoadError)

**Comment by renatocarvalho** [comment]
@tporto Conseguiu resolver o problema? Acredito que a gem tem dependencia sobre o slim. Porém, se está na dependência, acredito que deveria funcionar normalmente.

**Comment by tporto** [comment]
Não consegui fica dando esse erro de dependência do slim, sendo que não uso.
Em 18/03/2015 17:04, "Renato Carvalho" <notifications@github.com> escreveu:

**Comment by renatocarvalho** [comment]
@romulomachado Tem ideia do que pode estar rolando?

**Comment by tporto** [comment]
Aparentemente é que alguma gem de dependência não é compatível com o ruby
2.2
Em 18/03/2015 17:15, "Renato Carvalho" <notifications@github.com> escreveu:

**Comment by romulomachado** [comment]
Atualmente não oferecemos suporte a Haml, precisa do Slim pra rodar.

**Comment by tporto** [comment]
Então deve ser por isso. Pq uso o haml, pow deveria ter suporte essa gem é
muito boa.
Em 18/03/2015 17:18, "Rômulo Machado" <notifications@github.com> escreveu:

**Comment by renatocarvalho** [comment]
@tporto A gente utilizava o `haml` antes. Só que o `slim` é melhor ainda. Fechando essa issue ;)
